"""audit_local_split.py (S002 P1) — flag wiki visibility misclassification suspects.

Per `tasks/plans/portfolio-folder-structure-spec.md` section (d) "New
scripts". Stub-level scan for misclassification between
`wiki.<name>/local/` (confidential) and `wiki.<name>/git/` (public).

Two heuristics (intentionally lightweight; semantic decisions stay
with the Librarian agent):

    A. Pages in `git/` containing forbidden-terms markers — these
       MIGHT belong in local/. Match against
       `Biz.Automation/wikisys.<name>/_config/forbidden_terms.yaml`
       if present.

    B. Pages in `local/` containing no internal markers and only public
       content patterns — these MIGHT be promotable to git/.

These are HINTS, not decisions. The Librarian agent reviews and
classifies. Spec (d) Change 2: "Visibility classification (this
content belongs in `local/` or `git/`?) is a semantic decision —
Agent owns it; this script surfaces suspects."

Output:
    Dashboard at `<root>/Biz.Automation/wikisys.<name>/_dashboards/local-split.md`.

Out of scope (deferred to S004): TF-IDF similarity scoring,
embedding-based visibility classifiers, per-topic policy overrides.

Exit codes:
    0  no findings
    1  one or more visibility-misclass suspects
    2  no wiki.*/ at all (nothing to scan)
"""
# @component Codex[validators]

import argparse
import sys
from pathlib import Path
from typing import List, NamedTuple, Optional


class Finding(NamedTuple):
    suspect_type: str   # "private-leak-in-git" | "public-content-in-local"
    path: str           # relative to root
    matched_terms: List[str]


def _load_forbidden_terms(wikisys_dir: Optional[Path]) -> List[str]:
    """Read forbidden_terms.yaml if present; return list of terms.

    Minimal YAML walker — handles the canonical Codex form:
        forbidden_terms:
          - term: foo
            ...
          - term: bar
    """
    if wikisys_dir is None:
        return []
    config = wikisys_dir / "_config" / "forbidden_terms.yaml"
    if not config.is_file():
        return []
    terms: List[str] = []
    for line in config.read_text(encoding="utf-8").splitlines():
        stripped = line.strip()
        if stripped.startswith("- term:"):
            terms.append(stripped.split(":", 1)[1].strip().strip('"\''))
    return terms


def _scan_files_for_terms(directory: Path, terms: List[str]) -> List[tuple]:
    """Return [(file_path, [matched_terms]), ...]."""
    out = []
    if not directory.is_dir():
        return out
    for f in directory.rglob("*.md"):
        if not f.is_file():
            continue
        try:
            text = f.read_text(encoding="utf-8", errors="ignore").lower()
        except OSError:
            continue
        matched = [t for t in terms if t.lower() in text]
        if matched:
            out.append((f, matched))
    return out


def audit(root: Path) -> List[Finding]:
    findings: List[Finding] = []
    wikisys = next(root.glob("Biz.Automation/wikisys.*"), None)
    terms = _load_forbidden_terms(wikisys)

    for wiki_root in sorted(root.glob("wiki.*")):
        git_dir = wiki_root / "git"
        local_dir = wiki_root / "local"

        # Heuristic A: forbidden term in git/ → possible leak
        if terms:
            for path, matched in _scan_files_for_terms(git_dir, terms):
                findings.append(Finding(
                    suspect_type="private-leak-in-git",
                    path=str(path.relative_to(root)).replace("\\", "/"),
                    matched_terms=matched,
                ))

        # Heuristic B: page in local/ with no forbidden terms anywhere
        # → MIGHT be promotable. Stub: list local/ pages and note
        # forbidden-terms absence.
        if terms and local_dir.is_dir():
            for f in local_dir.rglob("*.md"):
                if not f.is_file():
                    continue
                try:
                    text = f.read_text(encoding="utf-8", errors="ignore").lower()
                except OSError:
                    continue
                if not any(t.lower() in text for t in terms):
                    findings.append(Finding(
                        suspect_type="public-content-in-local",
                        path=str(f.relative_to(root)).replace("\\", "/"),
                        matched_terms=[],
                    ))

    return findings


def render_dashboard(findings: List[Finding]) -> str:
    lines = [
        "# Local/Git Split Audit",
        "",
        "Generated by `audit_local_split.py`. Heuristic visibility-",
        "misclassification scan; semantic decisions defer to the",
        "Librarian agent.",
        "",
    ]
    if not findings:
        lines.extend(["**Status:** ✓ No visibility-misclass suspects.", ""])
        return "\n".join(lines)

    lines.append("**Status:** {} suspect(s).".format(len(findings)))
    lines.append("")
    lines.append("| Suspect type | Path | Matched terms |")
    lines.append("|---|---|---|")
    for f in findings:
        terms_str = ", ".join("`" + t + "`" for t in f.matched_terms) if f.matched_terms else "—"
        lines.append("| {} | `{}` | {} |".format(
            f.suspect_type, f.path, terms_str
        ))
    lines.append("")
    return "\n".join(lines)


def _resolve_dashboard_path(root: Path, override: Optional[Path]) -> Path:
    if override is not None:
        return override
    wikisys = next(root.glob("Biz.Automation/wikisys.*"), None)
    if wikisys is None:
        return root / "local-split.md"
    return wikisys / "_dashboards" / "local-split.md"


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(prog="audit_local_split.py")
    parser.add_argument("--root", type=Path, default=Path.cwd())
    parser.add_argument("--dashboard", type=Path, default=None)
    args = parser.parse_args(argv)
    root = args.root.resolve()

    if not any(root.glob("wiki.*")):
        sys.stderr.write("no wiki.*/ at {}\n".format(root))
        return 2

    findings = audit(root)
    dashboard_path = _resolve_dashboard_path(root, args.dashboard)
    dashboard_path.parent.mkdir(parents=True, exist_ok=True)
    dashboard_path.write_text(render_dashboard(findings), encoding="utf-8")
    sys.stdout.write("Dashboard written: {}\n".format(dashboard_path))
    sys.stdout.write("Suspects: {}\n".format(len(findings)))
    return 0 if not findings else 1


if __name__ == "__main__":
    sys.exit(main())
