"""audit_gitignore.py (S002 P0) — verify canonical .gitignore patterns.

Per `tasks/plans/portfolio-folder-structure-spec.md` section (d) "New
scripts" and section (a) §"Variance allowance" `.gitignore` requirements.

Checks (per spec):
    1. If `wiki.*/` exists, `.gitignore` MUST exclude `wiki.*/local/`.
    2. If project-root `Local/` exists, `.gitignore` SHOULD exclude `Local/`.
    3. If `assets/` exists with heavy patterns possible, common
       heavy-file extensions should be excluded (warn-only):
           assets/**/*.mp4, *.mov, *.psd
    4. `.gitignore` exists at all.

Output:
    Dashboard at `<projectroot>/Biz.Automation/wikisys.<name>/_dashboards/gitignore.md`.

Exit codes:
    0  no findings
    1  one or more findings
    2  no .gitignore at all (block-level)
"""
# @component Codex[validators]

import argparse
import sys
from pathlib import Path
from typing import List, NamedTuple, Optional


class Finding(NamedTuple):
    severity: str   # "error" | "warning"
    rule: str       # "wiki-local-not-excluded" | "local-not-excluded" | "heavy-assets-not-excluded"
    message: str


def audit(root: Path) -> List[Finding]:
    findings: List[Finding] = []
    gitignore = root / ".gitignore"
    if not gitignore.exists():
        findings.append(Finding(
            severity="error",
            rule="gitignore-missing",
            message="No .gitignore at project root.",
        ))
        return findings

    text = gitignore.read_text(encoding="utf-8")

    # Rule 1: wiki.*/local/ must be excluded if any wiki.*/ exists
    if any(root.glob("wiki.*")):
        if "wiki.*/local/" not in text and "wiki.*/local" not in text:
            findings.append(Finding(
                severity="error",
                rule="wiki-local-not-excluded",
                message=(
                    "wiki.*/ exists but .gitignore does not exclude "
                    "`wiki.*/local/`. Add the pattern."
                ),
            ))

    # Rule 2: Local/ exclusion is recommended if Local/ exists
    if (root / "Local").exists():
        if "Local/" not in text and "/Local/" not in text:
            findings.append(Finding(
                severity="warning",
                rule="local-not-excluded",
                message=(
                    "Local/ exists at project root but .gitignore does "
                    "not exclude `Local/`. Recommended for non-wiki "
                    "confidential files (eddyandwolff pattern)."
                ),
            ))

    # Rule 3: heavy-asset patterns warn if assets/ exists
    if (root / "assets").exists():
        heavy_patterns = ("*.mp4", "*.mov", "*.psd")
        if not any(p in text for p in heavy_patterns):
            findings.append(Finding(
                severity="warning",
                rule="heavy-assets-not-excluded",
                message=(
                    "assets/ exists but .gitignore has no heavy-file "
                    "patterns (.mp4/.mov/.psd). Recommended to prevent "
                    "accidental large-file commits."
                ),
            ))

    return findings


def render_dashboard(findings: List[Finding], root: Path) -> str:
    lines = [
        "# Gitignore Audit",
        "",
        "Generated by `audit_gitignore.py`. Verifies canonical "
        "portfolio-spec gitignore requirements.",
        "",
    ]
    errors = [f for f in findings if f.severity == "error"]
    warnings = [f for f in findings if f.severity == "warning"]

    if not findings:
        lines.extend(["**Status:** ✓ All gitignore rules satisfied.", ""])
        return "\n".join(lines)

    lines.append("**Status:** {} error(s), {} warning(s).".format(
        len(errors), len(warnings)
    ))
    lines.append("")
    lines.append("| Severity | Rule | Message |")
    lines.append("|---|---|---|")
    for f in findings:
        lines.append("| {} | {} | {} |".format(f.severity, f.rule, f.message))
    lines.append("")
    return "\n".join(lines)


def _resolve_dashboard_path(root: Path, override: Optional[Path]) -> Path:
    if override is not None:
        return override
    wikisys = next(root.glob("Biz.Automation/wikisys.*"), None)
    if wikisys is None:
        return root / "gitignore.md"
    return wikisys / "_dashboards" / "gitignore.md"


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(prog="audit_gitignore.py")
    parser.add_argument("--root", type=Path, default=Path.cwd())
    parser.add_argument("--dashboard", type=Path, default=None)
    args = parser.parse_args(argv)
    root = args.root.resolve()

    findings = audit(root)

    if any(f.rule == "gitignore-missing" for f in findings):
        sys.stderr.write("error: .gitignore missing at {}\n".format(root))
        return 2

    dashboard_path = _resolve_dashboard_path(root, args.dashboard)
    dashboard_path.parent.mkdir(parents=True, exist_ok=True)
    dashboard_path.write_text(render_dashboard(findings, root), encoding="utf-8")
    sys.stdout.write("Dashboard written: {}\n".format(dashboard_path))
    sys.stdout.write("Findings: {} (errors={}, warnings={})\n".format(
        len(findings),
        sum(1 for f in findings if f.severity == "error"),
        sum(1 for f in findings if f.severity == "warning"),
    ))

    return 0 if not findings else 1


if __name__ == "__main__":
    sys.exit(main())
