"""audit_doc_pairing.py (S002 P0) — detect unpaired automations / orphan doc folders.

Per `tasks/plans/portfolio-folder-structure-spec.md` section (d) "New
scripts" and `wiki.codex/git/codex/CODEX_LIBRARIAN.md` Pairing-Audit
operation (S002 B7 extension).

Pairing contract:
    For every `Biz.Automation/<automationname>/` folder, there should be
    a paired `wiki.<projectname>/git/<automationname>.doc/` folder.
    Names match modulo the `.doc` suffix.

Findings:
    - **Unpaired automation:** `Biz.Automation/foo/` exists but no
      `wiki.<name>/git/foo.doc/` partner.
    - **Orphan doc folder:** `wiki.<name>/git/bar.doc/` exists but no
      `Biz.Automation/bar/` partner.

Output:
    A markdown dashboard at `<rootpath>/Biz.Automation/wikisys.<name>/_dashboards/doc-pairing.md`
    (or wherever the project's dashboards root resolves).

CLI:
    python audit_doc_pairing.py --root <projectroot>
        [--dashboard <path>] [--json]

Exit codes:
    0  no findings
    1  one or more findings emitted
    2  malformed tree (e.g. no Biz.Automation/, no wiki.*/)
"""

import argparse
import json
import sys
from pathlib import Path
from typing import List, NamedTuple, Optional


class Finding(NamedTuple):
    kind: str          # "unpaired-automation" | "orphan-doc-folder"
    path: str          # display path
    suggested_pair: str  # what the partner should be


def _find_biz_automation_dirs(root: Path) -> List[Path]:
    """Return automation folder paths under Biz.Automation/.

    Skips wikisys.<name>/ (system folder, not an automation) and any
    folder starting with `_` (private) or `.` (hidden).
    """
    biz = root / "Biz.Automation"
    if not biz.is_dir():
        return []
    out = []
    for entry in sorted(biz.iterdir()):
        if not entry.is_dir():
            continue
        if entry.name.startswith(("wikisys.", "_", ".")):
            continue
        out.append(entry)
    return out


def _find_doc_folders(root: Path) -> List[Path]:
    """Return `<name>.doc/` folders under any wiki.*/git/."""
    out = []
    for wiki in sorted(root.glob("wiki.*/git")):
        if not wiki.is_dir():
            continue
        for entry in sorted(wiki.iterdir()):
            if entry.is_dir() and entry.name.endswith(".doc"):
                out.append(entry)
    return out


def audit(root: Path) -> List[Finding]:
    """Run the pairing audit; return list of findings (empty = clean)."""
    findings: List[Finding] = []
    automations = _find_biz_automation_dirs(root)
    doc_folders = _find_doc_folders(root)
    doc_names = {p.name[:-4] for p in doc_folders}  # strip ".doc"
    auto_names = {p.name for p in automations}

    for auto_path in automations:
        if auto_path.name not in doc_names:
            # Suggest the most-likely pair location: the first wiki.*/git/
            wiki_git = next(root.glob("wiki.*/git"), None)
            suggested = (
                str(wiki_git / (auto_path.name + ".doc")) if wiki_git
                else "wiki.<projectname>/git/" + auto_path.name + ".doc"
            )
            findings.append(Finding(
                kind="unpaired-automation",
                path=str(auto_path.relative_to(root)),
                suggested_pair=suggested,
            ))

    for doc_path in doc_folders:
        bare = doc_path.name[:-4]
        if bare not in auto_names:
            suggested = str(root / "Biz.Automation" / bare)
            findings.append(Finding(
                kind="orphan-doc-folder",
                path=str(doc_path.relative_to(root)),
                suggested_pair=suggested,
            ))

    return findings


def render_dashboard(findings: List[Finding], root: Path) -> str:
    """Emit findings as a markdown dashboard."""
    lines = [
        "# Doc Pairing Audit",
        "",
        "Generated by `audit_doc_pairing.py`. Per spec (d) "
        "Pairing-Audit operation.",
        "",
        "Contract: every `Biz.Automation/<name>/` pairs with "
        "`wiki.<projectname>/git/<name>.doc/`.",
        "",
    ]
    if not findings:
        lines.extend(["**Status:** ✓ All automations paired. No orphan doc folders.", ""])
        return "\n".join(lines)

    lines.append("**Status:** {} finding(s).".format(len(findings)))
    lines.append("")
    lines.append("| Finding | Path | Suggested pair |")
    lines.append("|---|---|---|")
    for f in findings:
        lines.append("| {} | `{}` | `{}` |".format(
            f.kind, f.path, f.suggested_pair
        ))
    lines.append("")
    return "\n".join(lines)


def _resolve_dashboard_path(root: Path, override: Optional[Path]) -> Path:
    if override is not None:
        return override
    # Default: Biz.Automation/wikisys.<projectname>/_dashboards/doc-pairing.md
    wikisys = next(root.glob("Biz.Automation/wikisys.*"), None)
    if wikisys is None:
        # Library-internal case (no Biz.Automation/) — fallback at root
        return root / "doc-pairing.md"
    return wikisys / "_dashboards" / "doc-pairing.md"


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(prog="audit_doc_pairing.py")
    parser.add_argument("--root", type=Path, default=Path.cwd(),
                        help="Project root (default cwd).")
    parser.add_argument("--dashboard", type=Path, default=None,
                        help="Override dashboard output path.")
    parser.add_argument("--json", action="store_true",
                        help="Emit findings as JSON to stdout instead of dashboard.")
    args = parser.parse_args(argv)

    root = args.root.resolve()
    if not (root / "Biz.Automation").is_dir() and not any(root.glob("wiki.*")):
        sys.stderr.write(
            "error: {} does not look like a canonical project root "
            "(missing both Biz.Automation/ and wiki.*/)\n".format(root)
        )
        return 2

    findings = audit(root)

    if args.json:
        sys.stdout.write(json.dumps(
            [{"kind": f.kind, "path": f.path, "suggested_pair": f.suggested_pair}
             for f in findings],
            indent=2,
        ) + "\n")
    else:
        dashboard_path = _resolve_dashboard_path(root, args.dashboard)
        dashboard_path.parent.mkdir(parents=True, exist_ok=True)
        dashboard_path.write_text(render_dashboard(findings, root), encoding="utf-8")
        sys.stdout.write("Dashboard written: {}\n".format(dashboard_path))
        sys.stdout.write("Findings: {}\n".format(len(findings)))

    return 0 if not findings else 1


if __name__ == "__main__":
    sys.exit(main())
