"""audit_assets.py (S002 P1) — find heavy / unignored assets.

Per `tasks/plans/portfolio-folder-structure-spec.md` section (d) "New
scripts". Scans `<root>/assets/` for files exceeding a size threshold
(configurable; default 5MB) and cross-references `.gitignore` to flag
heavy files that aren't excluded.

Out of scope (deferred to S004): duplicate-hash detection,
deep-dependency tracking, per-folder size budgets.

Output:
    Dashboard at `<root>/Biz.Automation/wikisys.<name>/_dashboards/assets.md`.

Exit codes:
    0  no findings
    1  one or more heavy files not excluded by .gitignore
    2  no assets/ folder (nothing to scan)
"""
# @component Codex[validators]

import argparse
import fnmatch
import sys
from pathlib import Path
from typing import List, NamedTuple, Optional


DEFAULT_HEAVY_THRESHOLD_BYTES = 5 * 1024 * 1024  # 5MB


class Finding(NamedTuple):
    path: str           # relative to root
    size_bytes: int
    excluded: bool      # is this file gitignored?


def _load_gitignore_patterns(gitignore: Path) -> List[str]:
    if not gitignore.exists():
        return []
    out = []
    for line in gitignore.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if line and not line.startswith("#"):
            out.append(line)
    return out


def _is_excluded(rel_path: str, patterns: List[str]) -> bool:
    """Coarse check — fnmatch against each pattern. Conservative (false-positive OK)."""
    for p in patterns:
        if fnmatch.fnmatch(rel_path, p):
            return True
        # Wildcard patterns like "assets/**/*.mp4" — collapse to suffix match.
        if "**" in p:
            suffix = p.split("**")[-1].strip("/")
            if suffix and fnmatch.fnmatch(rel_path, "*" + suffix):
                return True
    return False


def audit(root: Path, threshold: int = DEFAULT_HEAVY_THRESHOLD_BYTES) -> List[Finding]:
    """Walk assets/; flag heavy files (size > threshold)."""
    assets = root / "assets"
    if not assets.is_dir():
        return []
    patterns = _load_gitignore_patterns(root / ".gitignore")
    findings: List[Finding] = []
    for f in assets.rglob("*"):
        if not f.is_file():
            continue
        try:
            size = f.stat().st_size
        except OSError:
            continue
        if size < threshold:
            continue
        rel = str(f.relative_to(root)).replace("\\", "/")
        excluded = _is_excluded(rel, patterns)
        findings.append(Finding(path=rel, size_bytes=size, excluded=excluded))
    return findings


def render_dashboard(findings: List[Finding], threshold: int) -> str:
    lines = [
        "# Assets Audit",
        "",
        "Generated by `audit_assets.py`. Threshold: {} bytes ({:.1f} MB).".format(
            threshold, threshold / (1024 * 1024)
        ),
        "",
    ]
    if not findings:
        lines.extend(["**Status:** ✓ No heavy files in assets/.", ""])
        return "\n".join(lines)

    unexcluded = [f for f in findings if not f.excluded]
    lines.append("**Status:** {} heavy file(s); {} not gitignored.".format(
        len(findings), len(unexcluded)
    ))
    lines.append("")
    lines.append("| Path | Size (MB) | Gitignored? |")
    lines.append("|---|---|---|")
    for f in findings:
        lines.append("| `{}` | {:.2f} | {} |".format(
            f.path, f.size_bytes / (1024 * 1024),
            "✓" if f.excluded else "✗",
        ))
    lines.append("")
    return "\n".join(lines)


def _resolve_dashboard_path(root: Path, override: Optional[Path]) -> Path:
    if override is not None:
        return override
    wikisys = next(root.glob("Biz.Automation/wikisys.*"), None)
    if wikisys is None:
        return root / "assets-audit.md"
    return wikisys / "_dashboards" / "assets.md"


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(prog="audit_assets.py")
    parser.add_argument("--root", type=Path, default=Path.cwd())
    parser.add_argument("--threshold-bytes", type=int,
                        default=DEFAULT_HEAVY_THRESHOLD_BYTES)
    parser.add_argument("--dashboard", type=Path, default=None)
    args = parser.parse_args(argv)
    root = args.root.resolve()

    if not (root / "assets").is_dir():
        sys.stderr.write("no assets/ at {}\n".format(root))
        return 2

    findings = audit(root, threshold=args.threshold_bytes)
    dashboard_path = _resolve_dashboard_path(root, args.dashboard)
    dashboard_path.parent.mkdir(parents=True, exist_ok=True)
    dashboard_path.write_text(
        render_dashboard(findings, args.threshold_bytes),
        encoding="utf-8",
    )
    sys.stdout.write("Dashboard written: {}\n".format(dashboard_path))
    unexcluded = sum(1 for f in findings if not f.excluded)
    sys.stdout.write("Heavy files: {} | Not gitignored: {}\n".format(
        len(findings), unexcluded
    ))
    return 0 if unexcluded == 0 else 1


if __name__ == "__main__":
    sys.exit(main())
