#!/usr/bin/env python3
"""Generate tasks/board.md — a read-only, state-grouped Kanban VIEW (framework/19; council-locked).

Council verdict (tasks/council/2026-06-06-unified-board-format.md): do NOT make the markdown
sections the authoritative task state — that reintroduces the two-writer race framework/19 removed
(the board would lie the moment the driver advances state in the log; double-pick risk; the
"autonomous" lane erodes the human-merge invariant under skim). Instead KEEP `tasks/todo.md` as the
operator's single-writer intent surface and the log authoritative, and GENERATE this 6-section view
from `todo.md` + `tasks/orchestrator-log.jsonl` so **position == truth** (it is rendered from truth).

This mirrors `scripts/sync_tasks_to_wiki.py` (generated, do-not-edit, `--check` drift guard). The
render is pure; the only I/O is the thin board read + the generated write. Stdlib only. Tested in
tests/test_render_board.py.
"""
from __future__ import annotations

import argparse
import sys
from datetime import datetime
from pathlib import Path
from typing import Optional, Sequence

_SCRIPTS = Path(__file__).resolve().parent
sys.path.insert(0, str(_SCRIPTS))

import task_state as ts          # noqa: E402
import task_driver as td         # noqa: E402

# (section title, the machine states it groups, blurb). Order is the rendered column order.
# The lane is named "Ready to Draft (autonomous)" -- draft-only, never "execute/ship" (council #3).
SECTIONS: tuple = (
    ("Ready to Draft (autonomous)", (ts.READY,),
     "Scored + eligible. A Routine may DRAFT these unattended (no human review to start). "
     "The PR is still merged by a human."),
    ("In Progress", (ts.IN_PROGRESS,),
     "Being worked now. A Routine-triggered draft carries a claim/run-id; an operator-worked item "
     "won't."),
    ("Needs Human Review", (ts.FOR_REVIEW, ts.NEEDS_OPERATOR),
     "Awaiting your review/merge (a draft PR or a built item pending sign-off), OR scored as "
     "needing human judgment (Level-2+ / rails / unclear)."),
    ("Proposed / Needs Scoring", (ts.PROPOSED, ts.SCORED),
     "New/discovered tasks awaiting LLM-Council + Delta-Force scoring."),
    ("Backlog", (ts.BACKLOG,),
     "The large lower-priority pool."),
    ("Done + Learnings", (ts.DONE, ts.SUPERSEDED),
     "Completed (operator-merged) or superseded. Key lessons -> tasks/lessons.md."),
)

_PRIORITY_RANK = {"critical": 3, "high": 2, "medium": 1, "low": 0, "none": -1}


def _render_item(t: "ts.Task", state: str, transitions: Sequence[dict], now: datetime) -> str:
    meta: list[str] = []
    if t.priority and t.priority != "none":
        meta.append(f"priority: {t.priority}")
    if t.score is not None:
        meta.append(f"DFTS {t.score}")
    if t.category:
        meta.append(t.category)
    if state == ts.IN_PROGRESS:
        claim = td.active_claim(t.title, transitions, now=now)
        if claim and claim.get("run_id"):
            meta.append(f"claim {claim['run_id']}")
    if state == ts.FOR_REVIEW:
        meta.append("awaiting your review/merge")
    line = f"- **{t.title}**"
    if meta:
        line += " — " + " · ".join(meta)
    return line


def render_board(board_tasks: Sequence["ts.Task"], transitions: Sequence[dict], *,
                 now: Optional[datetime] = None) -> str:
    """Render the 6-section state-grouped board from the operator's tasks + the log. Pure.

    Each task's canonical state is the log overlay (`task_driver.current_state`) over its board
    state, so In-Progress / Ready / Done reflect the authoritative log + PR state, not the markdown.
    """
    now = now or td._utcnow()
    by_state: dict[str, list] = {}
    for t in board_tasks:
        st = td.current_state(t.title, transitions, board_state=t.state)
        by_state.setdefault(st, []).append((t, st))

    lines = [
        "# EMCC Unified Tasks (generated view)",
        "",
        "> GENERATED by `scripts/render_board.py` from `tasks/todo.md` + "
        "`tasks/orchestrator-log.jsonl`. **DO NOT EDIT** — regenerated; your edits are overwritten.",
        "> Edit `tasks/todo.md` for intent/priority; the autonomous lifecycle "
        "(Ready/In-Progress/claims) is driven through the log. Here, position == truth.",
        "",
    ]
    for title, states, blurb in SECTIONS:
        items = [pair for s in states for pair in by_state.get(s, [])]
        lines.append(f"## {title}")
        lines.append(f"_{blurb}_")
        lines.append("")
        if not items:
            lines.append("_(none)_")
            lines.append("")
            continue
        for t, st in sorted(items, key=lambda p: _PRIORITY_RANK.get(p[0].priority, -1), reverse=True):
            lines.append(_render_item(t, st, transitions, now))
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def build(root: Path, tasks_dir: str = "tasks") -> str:
    base = root / tasks_dir
    todo = base / "todo.md"
    log = base / "orchestrator-log.jsonl"
    board = ts.parse_todo(todo) if todo.is_file() else []
    transitions = td.read_transitions(log)
    return render_board(board, transitions)


def main(argv: Optional[list] = None) -> int:
    p = argparse.ArgumentParser(prog="render_board", description=__doc__)
    p.add_argument("--root", default=".", help="repo root (default: cwd)")
    p.add_argument("--tasks-dir", default="tasks",
                   help="the tasks directory holding todo.md/orchestrator-log.jsonl/board.md "
                        "(default: tasks; use 'Tasks' for repos that capitalize it, e.g. tat_app)")
    p.add_argument("--check", action="store_true", help="exit 1 if board.md is stale (CI drift guard)")
    args = p.parse_args(argv)
    root = Path(args.root)
    content = build(root, args.tasks_dir)
    out = root / args.tasks_dir / "board.md"
    if args.check:
        existing = out.read_text(encoding="utf-8") if out.is_file() else ""
        if existing != content:
            print(f"{out} is stale — run: python scripts/render_board.py --tasks-dir {args.tasks_dir}",
                  file=sys.stderr)
            return 1
        print(f"{out}: in sync")
        return 0
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(content, encoding="utf-8")
    print(f"wrote {out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
